### ISSUE TITLE
undefined method 'enriched?' for #<Hash:0x007fcbd9ea2bd8>

### ISSUE THREAD

**Issue by shaam48** [GetStream/stream-rails#72]
So, I get the following error when trying to load my notification_feed:

undefined method `key?' for #<Array:0x007fcdf7bf0118>

Where it is erroring in the gem:
```
stream_rails (2.4.0) lib/stream_rails/renderable.rb:28:in `block in render_aggregated'
stream_rails (2.4.0) lib/stream_rails/renderable.rb:28:in `map'
stream_rails (2.4.0) lib/stream_rails/renderable.rb:28:in `render_aggregated'
stream_rails (2.4.0) lib/stream_rails/renderable.rb:12:in `render'
stream_rails (2.4.0) lib/stream_rails/utils/view_helpers.rb:7:in `render_activity'
```

My Code:
notifications.html.erb:
```
<div>
    <h1>Notifications</h1>
    <div class="row">
      <div class="col-md-8">
            <% @activities.each do |activity| %>
        <%= render_activity activity %>
      <% end %>
        </div>
    </div>
</div>
```
notifications_controller.rb:
```
def notifications
    @user = current_user
    enricher = StreamRails::Enrich.new
    feed = StreamRails.feed_manager.get_notification_feed(@user.id)
    results = feed.get()['results']
    @activities = enricher.enrich_activities(results)
  end
```

**Comment by shaam48** [comment]
I've created a PR solving the issue #73
